# Generated by Django 4.1 on 2022-10-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagename', models.CharField(max_length=50, verbose_name='imagename')),
                ('portno', models.IntegerField(verbose_name='portno')),
            ],
        ),
    ]
