# Generated by Django 4.1 on 2022-10-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunningInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.TextField()),
                ('owner', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('status', models.TextField(choices=[('deploying', 'Deploying'), ('running', 'Running')], default='deploying')),
            ],
        ),
        migrations.AlterField(
            model_name='info',
            name='imagename',
            field=models.CharField(max_length=1000, verbose_name='imagename'),
        ),
    ]
