# Generated by Django 4.1 on 2022-10-24 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_runninginstance_alter_info_imagename'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RunningInstance',
        ),
    ]
